/**
 * SafeHold scoring — TypeScript mirror of `computeScore` in
 * src/SafeHoldScore_1.sol.
 *
 * Both must agree. The contract is the auditable version anyone can verify on
 * Snowtrace; this one runs server-side so the UI does not wait on a chain read.
 * Integer arithmetic and the same basis-point inputs are used deliberately so
 * the two cannot drift.
 *
 * All percentages are basis points: 10000 bps = 100%.
 */

export const PROXIMITY_WINDOW_DAYS = 30;
export const K1_NUM = 23;
export const K1_DEN = 10;
export const SEVERITY_BASE = 2000;
export const ACTIVITY_MAX_PENALTY = 8;
export const BASELINE_PENALTY = 18;
const BPS = 10_000;

export type ScoreInputs = {
  /** % of circulating supply unlocking, in bps (1800 = 18%) */
  unlockPercentBps: number;
  /** whole days until that unlock */
  daysUntilUnlock: number;
  /** avg price drop after similar past unlocks, in bps. 0 when unknown. */
  historicalDropBps?: number;
  /** how elevated on-chain activity is vs baseline, in bps. 0 = normal. */
  activityBps?: number;
};

/**
 * Integer division, matching Solidity's truncating `/`.
 * Using Math.floor rather than plain division is what keeps the two
 * implementations byte-for-byte in agreement.
 */
function computeScoreExact(i: ScoreInputs): number {
  const unlockPercentBps = Math.max(0, Math.min(BPS, Math.trunc(i.unlockPercentBps)));
  const daysUntilUnlock = Math.max(0, Math.trunc(i.daysUntilUnlock));
  const historicalDropBps = Math.max(0, Math.min(BPS, Math.trunc(i.historicalDropBps ?? 0)));
  const activityBps = Math.max(0, Math.min(BPS, Math.trunc(i.activityBps ?? 0)));

  const proximityWeightBps =
    daysUntilUnlock >= PROXIMITY_WINDOW_DAYS
      ? 0
      : Math.floor(((PROXIMITY_WINDOW_DAYS - daysUntilUnlock) * BPS) / PROXIMITY_WINDOW_DAYS);

  // One fraction, one division — multiply before dividing to keep precision,
  // exactly as the contract does.
  const numerator =
    unlockPercentBps * proximityWeightBps * K1_NUM * (SEVERITY_BASE + historicalDropBps);
  const denominator = 100 * BPS * K1_DEN * SEVERITY_BASE;

  const unlockPenalty = Math.floor(numerator / denominator);
  const activityPenalty = Math.floor((activityBps * ACTIVITY_MAX_PENALTY) / BPS);
  const totalPenalty = unlockPenalty + activityPenalty + BASELINE_PENALTY;

  return totalPenalty >= 100 ? 0 : 100 - totalPenalty;
}

export type Band = "safe" | "watch" | "risk";

export type Verdict = {
  score: number;
  band: Band;
  headline: string;
  detail: string;
};

function band(score: number): Band {
  if (score >= 70) return "safe";
  if (score >= 40) return "watch";
  return "risk";
}

/**
 * The one-sentence explanation. Templated rather than generated by a model:
 * instant, free, and auditable — which matters more than phrasing variety when
 * the number it explains has to be defensible.
 */
export function verdict(
  inputs: ScoreInputs,
  opts: { hasUpcomingUnlock: boolean } = { hasUpcomingUnlock: true },
): Verdict {
  const score = computeScoreExact(inputs);
  const b = band(score);
  const pct = inputs.unlockPercentBps / 100;
  const days = inputs.daysUntilUnlock;

  if (!opts.hasUpcomingUnlock) {
    return {
      score,
      band: b,
      headline: "Safe to hold this week",
      detail: "No unlock scheduled in the data we track.",
    };
  }

  if (b === "safe") {
    return {
      score,
      band: b,
      headline: "Safe to hold this week",
      detail:
        days > PROXIMITY_WINDOW_DAYS
          ? `No unlock scheduled in the next ${PROXIMITY_WINDOW_DAYS} days.`
          : `Next unlock in ${days} days, ${fmtPct(pct)} of circulating supply.`,
    };
  }

  if (b === "watch") {
    return {
      score,
      band: b,
      headline: "Watch closely",
      detail: `${fmtPct(pct)} of circulating supply unlocks in ${days} days.`,
    };
  }

  return {
    score,
    band: b,
    headline: days <= 7 ? "High risk — unlock imminent" : "High risk",
    detail: `${fmtPct(pct)} of circulating supply unlocks in ${days} days.`,
  };
}

function fmtPct(pct: number): string {
  if (pct >= 10) return `${Math.round(pct)}%`;
  return `${pct.toFixed(2).replace(/\.?0+$/, "")}%`;
}

export { computeScoreExact as computeScore };
